name: Publish Package

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read
env:
  node: 22

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read package.json
        uses: actions/github-script@v7
        with:
            result-encoding: string
            script: |
                try {
                    const fs = require('fs')
                    const jsonString = fs.readFileSync('package.json')
                    var json = JSON.parse(jsonString);
                    core.exportVariable('version', json.version.toString())
                } catch(err) {
                    core.error("Error while reading or parsing package.json")
                    core.setFailed(err)
                }

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node }}
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed
      - run: npm install -g npm@latest

      - name: Publish package
        run: |
          echo "Publishing version ${{ env.version }}"
          mkdir package
          npm pack --pack-destination package
          ls -R package
          #   npm publish

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: edge-js-${{ env.version }}
          path: |
            package/edge-js-${{ env.version }}.tgz

    #   - name : Tag version
    #     run: |
    #       git tag v${{ env.version }}
    #       git push origin --tags
